Vagrant::Config.run do |config|
  config.vm.box = "ubuntu1110"

  # make this source tree visible in the VM so we can run current showoff
  config.vm.share_folder "showup", "/home/vagrant/showup", "../"

  # ensure that we have an actual presentation to work with
  config.vm.share_folder "host_root", "/home/vagrant/root", "/"

  # ensure that `apt-get update` is run before puppet installs packages
  config.vm.provision :shell, :inline => "sudo apt-get update"

  # let puppet configure all the apt packages
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "pdf.pp"
  end

  # install the few packages that need to be built from CPAN
  config.vm.provision :shell, :path => 'scripts/cpan.sh'

  # install ruby1.9.1 rubygems
  config.vm.provision :shell, :path => 'scripts/gems.sh'

  config.vm.forward_port 9090, 9090
end
