Vagrant::Config.run do |config|
  config.vm.box = "ubuntu1110"

  config.vm.share_folder "showup", "/home/vagrant/showup", "../"

  # ensure that `apt-get update` is run before puppet installs packages
  config.vm.provision :shell, :inline => "sudo apt-get update"

  # let puppet configure all the apt packages
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "pdf.pp"
  end

  # finally, install the few packages that need to be built from CPAN
  config.vm.provision :shell, :path => 'scripts/cpan.sh'
end
